<?php
/*
 * upload form template Medma_Avatar
 */
?>

<script type="text/javascript">
    /*
     * to preview image before actual upload  
     */
        
		$j = jQuery.noConflict(); 
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $j('#preview').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
    
</script>
<form action="<?php echo $this->getUploadUrl() ?>" method="post" enctype="multipart/form-data" >
    <div class="fieldset">  
        <h2 class="legend"><?php echo $this->__('Upload Avatar')?></h2>
        <ul class="form-list">
            <li> 
                <label for="file">Filename:</label>
                <input type="file" name="uploaded_file" id="file" onChange="readURL(this);"><br>
            </li>
            <li>
                <button type ="submit" name="submit" title="upload" class="button">
                    <span><span><?php echo $this->__('Upload') ?></span></span>
                </button>
            </li>
            <li>



                <?php if ($this->getAvatar()): ?> 
                    <div class="preview-wrapper">
                        <img id="preview" 
                             src="<?php if($this->getAvatar()){ echo $this->getAvatarPath(); } ?>" 
                             width="<?php echo $this->getWidth() ?>" 
                             height="<?php echo $this->getHeight() ?>"
                        />
                    </div>
                <?php endif ?>



            </li>    
        </ul>

    </div>
</form>

