<div class="entry-edit">
    <div class="entry-edit-head"><h4 class="icon-head head-customer-view"><?php echo Mage::helper('customer')->__('Personal Information') ?></h4></div>
    <fieldset>
        <table cellspacing="2" class="box-left">
            <tr>
                <td><strong><?php echo $this->__('Name') ?></strong></td>
                <td><?php echo $this->getCustomer()->getName(); ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Email') ?></strong></td>
                <td><?php echo $this->getCustomer()->getemail(); ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Last Logged In:') ?></strong></td>
                <td><?php echo $this->getLastLoginDate() ?> (<?php echo $this->getCurrentStatus() ?>)</td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Confirmed email:') ?></strong></td>
                <td><?php echo $this->getIsConfirmedStatus() ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Account Created on:') ?></strong></td>
                <td><?php echo $this->getCreateDate() ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Account Created in:') ?></strong></td>
                <td><?php echo $this->getCreatedInStore() ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Customer Group:') ?></strong></td>
                <td><?php echo $this->getGroupName() ?></td>
            </tr>
        </table>
        <address class="box-right">
            <strong><?php echo $this->__('Primary Billing Address') ?></strong><br/>
            <?php echo $this->getBillingAddressHtml() ?>
        </address>
    </fieldset>
</div>

<?php echo $this->getSalesHtml(); ?>