<div class="page-title">
    <h1><?php echo $this->__('Social Account Informations') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
 <div class="box">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Social Networking Information') ?></h2>
          <a href="<?php echo $this->getUrl('socialaccounts/index/index/') ?>" style="float:right;"><?php echo $this->__('Edit') ?></a>
        
         <?php if ($this->getFacebook()): ?> 
         <a href="http://www.facebook.com/<?php echo $this->getFacebookLink() ?>" target="_blank" ><img src="<?php echo $this->getSkinUrl('socialaccounts/images/facebook.png'); ?>" alt="<?php echo $this->getFacebookLink() ?>" height="36" width="36"/></a>
         <?php endif ?> 
         <?php if ($this->getTwitter()): ?> 
         <a href="https://twitter.com/<?php echo $this->getTwitterLink() ?>" target="_blank" ><img src="<?php echo $this->getSkinUrl('socialaccounts/images/twitter.png'); ?>" alt="<?php echo $this->getTwitterLink() ?>" height="36" width="36"/></a>
         <?php endif ?> 
         <?php if ($this->getPinterest()): ?> 
        <a href="http://www.pinterest.com/<?php echo $this->getPinterestLink() ?>" target="_blank" ><img src="<?php echo $this->getSkinUrl('socialaccounts/images/pinterest.png'); ?>" alt="<?php echo $this->getPinterestLink() ?>" height="36" width="36"/></a>
         <?php endif ?> 
         <?php if ($this->getInstagram()): ?> 
         <a href="http://instagram.com/<?php echo $this->getInstagramLink() ?>" target="_blank" ><img src="<?php echo $this->getSkinUrl('socialaccounts/images/instagram.png'); ?>" alt="<?php echo $this->getInstagramLink() ?>" height="36" width="36"/></a>
         <?php endif ?> 
         <?php if ($this->getGoogleplus()): ?> 
         <a href="https://plus.google.com/<?php echo $this->getGoogleplusLink() ?>" target="_blank" ><img src="<?php echo $this->getSkinUrl('socialaccounts/images/googleplus.png'); ?>" alt="<?php echo $this->getGoogleplusLink() ?>" height="36" width="36"/></a>
         <?php endif ?>
    </div>
</div>    
    

