<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>
<?php
/**
 * Template for filter items block
 *
 * @see Mage_Catalog_Block_Layer_Filter
 */
?>
<?php $item_url;  $item_values; $k=0; foreach ($this->getItems() as $_item): ?>
<?php if($_item->getName() == 'Size'):?>
      <?php 
		 
		   if (strpos($_item->getLabel(),'L') !== false):  
		    $item_values[$k]=substr($_item->getLabel(),0,strpos($_item->getLabel(),'L')); 
			$item_url[$k]=$this->urlEscape($_item->getUrl());
			$k=$k+1;
		   ?>  
   <?php  endif; ?>
  <?php endif; ?>
  <?php endforeach ?>
<ol>
    <?php $i = 1; $prv = 0; foreach ($this->getItems() as $_item): ?>
    <?php if(($_item->getName() == 'Size') && ($i == 1)): ?>
    	<li class="size-layer-title"><?php echo $this->__('Reg.') ?></li>
        <li class="size-layer-title"><?php echo $this->__('Long') ?></li>
     <?php endif; ?>
        <?php
        // GravDept: custom function to enable basic filter styling by type
        $gravdept_filterClass = "filter-" . strtolower( preg_replace("/[^a-zA-Z0-9]/", "", $_item->getName()) ) . "-" . strtolower( preg_replace("/[^a-zA-Z0-9]/", "", $_item->getLabel()) );
      ?>
        <?php if($_item->getName() == 'Size'):?>
			<?php $gravdept_filterClass = $gravdept_filterClass.' size-layer'; ?>
           <?php /*?> <?php if(preg_match("/[0-9]+[L]+/", $_item->getLabel()) == TRUE): ?>
            		<?php if(((($i%2)== 1) && ($prv != 0) )||($i==1)): ?>
                     	<li class="size-layer">&nbsp;</li>
                    <?php endif; ?> 
                    <?php $prv = 1; ?>
            <?php else: ?>
					<?php if(($prv == 0) && ($i > 1)): ?>
                     	<li class="size-layer">&nbsp;</li>
                    <?php endif; ?>
                     <?php $prv = 0; ?>
			<?php endif; ?>  <?php */?>
            
        <?php endif; ?>   
        
         <?php if($_item->getName() == 'Size'): ?>
       
            <?php if(preg_match("/[0-9]+[L]+/", $_item->getLabel()) == TRUE): ?>
             <?php else: 
			 if (in_array($_item->getLabel(), $item_values)): 
			 $key = array_search($_item->getLabel(), $item_values)
 			 ?>
      	<li class="<?php echo $gravdept_filterClass; ?>"> <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?> </a></li>
        <li class="<?php echo $gravdept_filterClass; ?>"> <a href="<?php echo  $item_url[$key] ?>"><?php echo $_item->getLabel()."L" ?> </a></li>
       <?php else: ?>
    	<li class="<?php echo $gravdept_filterClass; ?>"> <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?> </a></li>
		<li class="size-layer">&nbsp;</li>
       <?php  endif; ?> 
       <?php  endif; ?>
        <?php else: ?>      
        <li class="<?php echo $gravdept_filterClass; ?>">
            <?php if ($_item->getCount() > 0): ?>
                <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>">
                 <?php /*?> <?php if ($this->shouldDisplayProductCount()): ?>
                        <span class="count"><?php echo $_item->getCount() ?></span>
                    <?php endif; ?><?php */?>
                    
                    <?php echo $_item->getLabel() ?>
                    <?php /*echo $_item->getName()*/ ?>
                </a>
            <?php else: ?>
                <?php echo $_item->getLabel() ?>
            <?php endif; ?>
        </li>  
		<?php endif; ?>
       <?php $i=$i+1; ?>
    <?php endforeach ?>
</ol>