<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>
<?php
/**
 * Template for filter items block
 *
 * @see Mage_Catalog_Block_Layer_Filter
 */
?>

<ol>
    <?php $i = 1; foreach ($this->getItems() as $_item): ?>
    <?php if(($_item->getName() == 'Size') && ($i == 1)): ?>
    	<li class="size-layer-title"><?php echo $this->__('Reg.') ?></li>
        <li class="size-layer-title"><?php echo $this->__('Long') ?></li>
     <?php endif; ?>
        <?php
        // GravDept: custom function to enable basic filter styling by type
        $gravdept_filterClass = "filter-" . strtolower( preg_replace("/[^a-zA-Z0-9]/", "", $_item->getName()) ) . "-" . strtolower( preg_replace("/[^a-zA-Z0-9]/", "", $_item->getLabel()) );
      ?>
        <?php if($_item->getName() == 'Size'):?>
			<?php $gravdept_filterClass = $gravdept_filterClass.' size-layer'; ?>
            <?php if(preg_match("/[0-9]+[L]+/", $_item->getLabel()) == TRUE): ?>
            		<?php if(($i%2)== 1): ?>
                     	<li class="size-layer">&nbsp;</li>
                    <?php endif; ?> 
            <?php else: ?>
					<?php if(($i%2)== 0): ?>
                     	<li class="size-layer">&nbsp;</li>
                    <?php endif; ?>
			<?php endif; ?>  
            
        <?php endif; ?>         
        <li class="<?php echo $gravdept_filterClass; ?>">
            <?php if ($_item->getCount() > 0): ?>
                <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>">
                   <?php /*?> <?php if ($this->shouldDisplayProductCount()): ?>
                        <span class="count"><?php echo $_item->getCount() ?></span>
                    <?php endif; ?><?php */?>
                    
                    <?php echo $_item->getLabel() ?>
                    <?php /*echo $_item->getName()*/ ?>
                </a>
            <?php else: ?>
                <?php echo $_item->getLabel() ?>
            <?php endif; ?>
        </li>
       <?php $i++; ?>
    <?php endforeach ?>
</ol>