<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2011 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.1
*/
?>

<div class="tour">

	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('gravdept_tour_header')->toHtml() ?>
	
	<h1>Design</h1>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

	<div id="tour-design" class="grid">
		<div class="grid_6">
			<img src="<?php echo $this->getSkinUrl('media/tour/design/home.jpg') ?>" alt="Home" />
			<img src="<?php echo $this->getSkinUrl('media/tour/design/cart.jpg') ?>" alt="Cart" />
			<img src="<?php echo $this->getSkinUrl('media/tour/design/checkout.jpg') ?>" alt="Checkout" />
			<img src="<?php echo $this->getSkinUrl('media/tour/design/account.jpg') ?>" alt="Account" />
		</div>
	
		<div class="grid_6">
			<img src="<?php echo $this->getSkinUrl('media/tour/design/catalog.jpg') ?>" alt="Catalog" />
			<img src="<?php echo $this->getSkinUrl('media/tour/design/product.jpg') ?>" alt="Products" />
		</div>
	</div>

</div>
