<?php 
	$_code=$this->getMethodCode();
	$carrier = $this->getMethodInstance();
	$pickupData = $this->getQuote()->getPickupData();
	$_rate = $this->getRate();
	$storesData = $this->getAllStores(); 
	
?>
<ul class="form-list" id="shipping_form_<?php echo $_rate->getCode() ?>" style="display:none;">
    <li>
        <label for="<?php echo $_code ?>_store" class="required"><em>*</em><?php echo $this->__('Choose Store Location:') ?></label>
        <span class="input-box">
            <select class="required-entry" name="shipping_pickup[store_id]">
             <?php foreach($storesData as $item): ?>
            	<option value=<?php echo $item['id']; ?> <?php if($pickupData['store_id'] == $item['id']){ echo "selected=selected";} ?>><?php echo $item['name']; ?></option>
              <?php endforeach; ?>
            </select>
        </span>        
    </li>
</ul>