<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Sales Report'); ?></h3></td>
            <td align="right"><button onclick="document.location.href='<?php echo $this->getPrintUrl(); ?>'" class="scalable" type="button"><span><?php echo $this->__('Print'); ?></span></button></td>
        </tr>
    </table>
</div>

<?php echo $this->getGridParentHtml() ?>
