<?php

$_item = $this->getItem();

$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();

$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);

$naam = $this->htmlEscape($this->getProductName());
$naam = explode('-',$naam);
?>
<item><?php echo trim($naam[0]);?></item>
<item><?php echo trim($naam[1]);?></item>
<item><?php echo trim($naam[2]);?></item>
<item><?php if ($this->hasProductUrl()):?><a href="<?php echo $this->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getProductName()) ?>" class="product-image"><?php endif;?><img src="<?php echo $this->getProductThumbnail()->resize(75); ?>" width="20" height="20" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" /><?php if ($this->hasProductUrl()):?></a><?php endif;?></item>
<item><?php echo $this->getProductUrl() ?></item>

    <item><?php if ($isVisibleProduct): ?><a href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo $this->__('Edit item parameters') ?>"><?php echo $this->__('Edit') ?></a><?php endif ?></item>

        <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>

         <item><?php echo $_item->getCalculationPrice(); ?></item>

    <?php endif; ?>

     <item><input name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" title="<?php echo $this->__('Qty') ?>" class="qty align-c" maxlength="12" style="width: 30px !important;" /></item>
    <item><?php echo $this->getQty() ?></item>

    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>

    <item>

        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>

            <span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">

        <?php else: ?>

            <span class="cart-price">

        <?php endif; ?>



            <?php if ($canApplyMsrp): ?>

                <span class="cart-msrp-subtotal">--</span>

            <?php else: ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>

                    <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>

                <?php else: ?>

                    <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>

                <?php endif; ?>

            <?php endif; ?>



        </span>

        <?php if (Mage::helper('weee')->getApplied($_item)): ?>



            <div class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>

                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>

                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>

                    <?php endforeach; ?>

                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>

                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>

                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>

                    <?php endforeach; ?>

                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>

                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>

                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>

                    <?php endforeach; ?>

                <?php endif; ?>

            </div>



            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>

                <div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">

                    <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>

                </div>

            <?php endif; ?>

        <?php endif; ?>

    </item>

    <?php endif; ?>

    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>

    <item>

        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>

        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>

            <span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">

        <?php else: ?>

            <span class="cart-price">

        <?php endif; ?>



            <?php if ($canApplyMsrp): ?>

                <span class="cart-msrp-subtotal">--</span>

            <?php else: ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>

                    <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?>

                <?php else: ?>

                    <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>

                <?php endif; ?>

            <?php endif; ?>



        </span>





        <?php if (Mage::helper('weee')->getApplied($_item)): ?>



            <div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>

                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>

                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>

                    <?php endforeach; ?>

                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>

                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>

                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>

                    <?php endforeach; ?>

                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>

                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>

                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>

                    <?php endforeach; ?>

                <?php endif; ?>

            </div>



            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>

                <div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">

                    <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?></span>

                </div>

            <?php endif; ?>

        <?php endif; ?>

    </item>

    <?php endif; ?>

    <item><a href="<?php echo $this->getDeleteUrl()?>" title="<?php echo $this->__('Remove item')?>" class="btn-remove btn-remove2"><?php echo $this->__('Remove item')?></a></item>