<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>

<div id="footer">
	<div id="footer-bar">
		<div class="newsletter">
			<?php echo $this->getChildHtml('newsletter') ?>
		</div>
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_social_acumen')->toHtml() ?>
		<a class="top" href="#top" title="<?php echo $this->__('Return to top') ?>"><?php echo $this->__('Top') ?></a>		
	</div>
	

	<div id="footer-closer" class="grid">
		<div class="grid_8">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links_acumen')->toHtml() ?>
		</div>
		
		<?php /*?><div >
			<div class="switchers">
				<?php //echo $this->getChildHtml('store_switcher') ?>
				<?php //echo $this->getChildHtml('store_language') ?>
				<?php echo $this->getChildHtml('store_currency') ?>
			</div>
			
			<div class="legal">
				<p class="copyright">&copy; <?php echo date("Y") ?> <?php echo $this->getCopyright() ?></p>
			
				<p class="terms">
					<a href="<?php echo $this->getUrl('#') ?>"><?php echo $this->__('Terms Of Use') ?></a>
					<a href="<?php echo $this->getUrl('#') ?>"><?php echo $this->__('Privacy Policy') ?></a>
				</p>
			</div
		</div><?php */?>
        
	</div>
    <div class="copy-div">
     <div class="copy-outer">
    <p class="copyright">&copy; <?php echo date("Y") ?> <?php echo $this->getCopyright() ?></p>
    <div class="payment-icons-footer">
	        <span><?php echo $this->__('Pay with') ?></span>
    	    <?php echo $this->getChildHtml('gravdept_payment_icons'); ?>
	    </div>
        </div>
      </div>
</div>
