<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Product Share'); ?></h3></td>
        </tr>
    </table>
</div>

<script type="text/javascript">

    var closeModaleWindow = '<?php echo $this->__('Close') ?>';

</script>
<?php if( !Mage::app()->isSingleStoreMode() ): ?>
<?php echo $this->getChildHtml('store_switcher');?>
<?php endif;?>
<?php echo $this->getGridParentHtml() ?>
