<?php
/**
* Acumen for Magento
* http://gravitydept.com/to/acumen-magento
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  Copyright 2013 Gravity Department http://gravitydept.com
* @license    All rights reserved.
* @version    1.3.5
*/
?>

<?php if($this->getItems()->getSize()): ?>
	<div id="cross-sell" class="block grid-block">
		<div class="block-title">
		    <h2><?php echo $this->__('Complete Your Look'); ?></h2>
		</div>
	
		<div class="block-content">
		    <ul class="cross-sell-list">
    			<?php foreach ($this->getItems() as $_item): ?>
    				<li>
    					<a class="product-image" href="<?php echo $_item->getProductUrl(); ?>">
                            <img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(200, 200); ?>" alt="<?php echo $this->escapeHtml($_item->getName()); ?>" />
                        </a>
    					
    					<div>
    						<a class="product-name" href="<?php echo $_item->getProductUrl(); ?>"><?php echo $this->escapeHtml($_item->getName()); ?></a>
    						<?php echo $this->getPriceHtml($_item, true); ?>
    						<a class="button" href="<?php echo $this->getAddToCartUrl($_item); ?>"><?php echo $this->__('Add To Cart'); ?></a>
    					</div>
    				</li>
    			<?php endforeach; ?>
    		</ul>
    	</div>
	</div>
<?php endif ?>
